---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: hpaprescaler-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hpaprescaler-role-cluster
rules:
  - apiGroups: ["hepapi.com"]
    resources: ["hpaprescalers", "hpaprescalerprofiles", "hpaprescalers/status", "hpaprescalerprofiles/status"]
    verbs: ["*"]
  - apiGroups: ["", "events.k8s.io"]
    resources: ["events"]
    verbs: ["create", "watch", "list"]  
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hpaprescaler-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hpaprescaler-role-cluster
subjects:
  - kind: ServiceAccount
    name: hpaprescaler-sa
    namespace: {{ .Release.Namespace | quote }}
