
image:
  repository: "hepapi/hpa-prescaler-controller"
  pullPolicy: "Always"
  tag: "main"


configMap:
  enabled: true
  configValues:
    LOOP_INTERVAL_SECS: "60"
    LOOP_INITAL_DELAY_SECS: "10"
    GRACE_TIME_DELTA_MINS: "10"
    DEPLOY_ENV: "Production" 
    ARGOCD_ENDPOINT: "http://argocd-server.argocd"
    ARGOCD_TOKEN: ""
    ARGOCD_SSL_VERIFY: "false"
    KUBECONFIG_OR_SERVICE_ACCOUNT: "serviceaccount"
    DO_ACTUALLY_DELETE_OLD_PRESCALERS: "false"
    DELETE_OLD_PRESCALERS_AFTER_DAYS: "14"  # keep prescalers for N days
    OLD_PRESCALERS_CHECK_EVERY_N_MINUTES: "500"
    DO_CREATE_KUBERNETES_EVENTS: "false"
    GRACE_WINDOW_ALGORITHM_NAME: "accept_window_is_before_target_time"  # default
    # GRACE_WINDOW_ALGORITHM_NAME: "accept_window_is_after_target_time"
    ARGOCD_HEALTH_CHECK_TIMEOUT: "10"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: "hpa-prescaler-controller"

prometheusAlerts:
  enabled: true
  prescalerError:
    severity: "critical"
    for: "5s"
  podNotReady:
    severity: "critical"
    for: "2m"



resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}