apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hpaprescalerprofiles.hepapi.com
spec:
  scope: Namespaced
  group: hepapi.com
  names:
    kind: HpaPrescalerProfile
    plural: hpaprescalerprofiles
    singular: hpaprescalerprofile
    shortNames:
      - prescalerprofile
      - hpsprofile
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                minReplicas:
                  type: integer
                maxReplicas:
                  type: integer
              x-kubernetes-validations:
                - rule: "self.minReplicas < self.maxReplicas"
                  message: "minReplicas must be less than maxReplicas"
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
      - name: minReplicas
        type: integer
        jsonPath: .spec.minReplicas
      - name: maxReplicas
        type: integer
        jsonPath: .spec.maxReplicas
