apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hpaprescalers.hepapi.com
spec:
  scope: Namespaced
  group: hepapi.com
  names:
    kind: HpaPrescaler
    plural: hpaprescalers
    singular: hpaprescaler
    shortNames:
      - prescaler
      - hps
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              # x-kubernetes-preserve-unknown-fields: true
              type: object
              properties:
                argocdAppName:
                  type: string
                timeStart:
                  type: string
                targetProfileName:
                  type: string
            status:
              # x-kubernetes-preserve-unknown-fields: true
              type: object
              properties:
                state:
                  type: string
                  default: "PENDING"
                message:
                  type: string
                  default: ""
                processedAt:
                  type: string
                  default: ""
      additionalPrinterColumns:
        - name: ArgoApp
          type: string
          jsonPath: .spec.argocdAppName
        - name: Profile
          type: string
          jsonPath: .spec.targetProfileName
        - name: TargetTime
          type: string
          jsonPath: .spec.timeStart
        - name: State
          type: string
          jsonPath: .status.state
        - name: Message
          type: string
          jsonPath: .status.message
        - name: ProcessedAt
          type: string
          jsonPath: .status.processedAt