apiVersion: v1
kind: Secret
metadata:
  name: demo-charts-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  name: demo-charts
  url: file:///demo-charts
